/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import com.umg.proyect.model.Student;
import com.umg.proyect.util.SessionManager;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Asignaciones extends javax.swing.JFrame {
    private InicioSesion back;
    /**
     * Creates new form Asignacion
     */
    public Asignaciones() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/f.png");
        this.Imagen(this.lbllogo, "src/main/java/img/logo.png");
        this.Imagen(this.lblimg, "src/main/java/img/chico.png");
        this.Imagen(this.lblfondo, "src/main/java/img/cursos.png");
        this.Imagen(this.lblPintura, "src/main/java/img/pintura.png");
        this.Imagen(this.lblMusica, "src/main/java/img/musica.png");
        this.Imagen(this.lblIdioma, "src/main/java/img/idioma.png");
        this.Imagen(this.lbltec, "src/main/java/img/tec.png");
        this.Imagen(this.lbllogo, "src/main/java/img/logo.png");        
        cargarDatosUsuario();
    }
    public void setBack(InicioSesion back) {
        this.back = back;
    }
    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhorario = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblespecialidad = new javax.swing.JLabel();
        lblmodalidad = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        btnidioma = new javax.swing.JButton();
        lblPintura = new javax.swing.JLabel();
        btnMusica1 = new javax.swing.JButton();
        lblMusica = new javax.swing.JLabel();
        btnidioma1 = new javax.swing.JButton();
        lblIdioma = new javax.swing.JLabel();
        btntec = new javax.swing.JButton();
        lbltec = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        lbltec1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡BIENVENIDO!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 360, 70));

        lblhorario.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblhorario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 190, 30));

        lblnombre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 320, 30));

        lblcurso.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblcurso.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 30));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecciona el Curso al que te deseas asignar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        lblespecialidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblespecialidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 190, 30));

        lblmodalidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblmodalidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblmodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 30));
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 340, 380));

        btnBack.setText("Regreso");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("****");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 210, -1));

        lblCarnet.setForeground(new java.awt.Color(255, 255, 255));
        lblCarnet.setText("****");
        getContentPane().add(lblCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, -1));

        btnidioma.setBackground(new java.awt.Color(51, 51, 255));
        btnidioma.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnidioma.setForeground(new java.awt.Color(255, 255, 255));
        btnidioma.setText("Inscribirme");
        btnidioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidiomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 150, 30));
        getContentPane().add(lblPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 120));

        btnMusica1.setBackground(new java.awt.Color(51, 51, 255));
        btnMusica1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnMusica1.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica1.setText("Inscribirme");
        btnMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusica1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMusica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 150, 30));
        getContentPane().add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, 130));

        btnidioma1.setBackground(new java.awt.Color(51, 51, 255));
        btnidioma1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnidioma1.setForeground(new java.awt.Color(255, 255, 255));
        btnidioma1.setText("Inscribirme");
        btnidioma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidioma1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnidioma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 150, 30));
        getContentPane().add(lblIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 120, 100));

        btntec.setBackground(new java.awt.Color(51, 51, 255));
        btntec.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btntec.setForeground(new java.awt.Color(255, 255, 255));
        btntec.setText("Inscribirme");
        btntec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntecActionPerformed(evt);
            }
        });
        getContentPane().add(btntec, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 150, 30));
        getContentPane().add(lbltec, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 130, 100));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));
        getContentPane().add(lbltec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 150, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnidiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidiomaActionPerformed
        CIdiomas idio= new CIdiomas();
        idio.setBack(this);
        idio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnidiomaActionPerformed

    private void btnMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusica1ActionPerformed
        CMusica idio= new CMusica();
        idio.setBack(this);
        idio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMusica1ActionPerformed

    private void btnidioma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidioma1ActionPerformed
        CMusica idio= new CMusica();
        idio.setBack(this);
        idio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnidioma1ActionPerformed

    private void btntecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntecActionPerformed
        CTec idio= new CTec();
        idio.setBack(this);
        idio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btntecActionPerformed

private void cargarDatosUsuario() {
    if (SessionManager.getUserType().equals("STUDENT")) {
        Student student = SessionManager.getCurrentStudent();
        lblNombre.setText("Estudiante: " + student.getNombre());
        lblCarnet.setText("Carnet: " + student.getCarnet());
    }
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignaciones().setVisible(true);
            }
        });
    }
    
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMusica1;
    private javax.swing.JButton btnidioma;
    private javax.swing.JButton btnidioma1;
    private javax.swing.JButton btntec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPintura;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblespecialidad;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblmodalidad;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltec;
    private javax.swing.JLabel lbltec1;
    // End of variables declaration//GEN-END:variables
}
