/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Asignacion extends javax.swing.JFrame {

    /**
     * Creates new form Asignacion
     */
    public Asignacion() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/f.png");
        this.Imagen(this.lbllogo, "src/main/java/img/logo.png");
        this.Imagen(this.lblimg, "src/main/java/img/chico.png");
    }
    
    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblhorario = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblcurso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblespecialidad = new javax.swing.JLabel();
        lblmodalidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡BIENVENIDO!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 360, 70));

        lblhorario.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblhorario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 190, 30));

        lblnombre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 320, 30));

        lblcurso.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblcurso.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 30));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Al curso de");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Especialidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        lblespecialidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblespecialidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 190, 30));

        lblmodalidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblmodalidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblmodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, 30));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modalidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 340, 380));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignacion().setVisible(true);
            }
        });
    }
    
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblcurso;
    private javax.swing.JLabel lblespecialidad;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblmodalidad;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
