/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/bienvenida.png");
    }
    
    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEstudiante = new javax.swing.JButton();
        btnMestro = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstudiante.setBackground(new java.awt.Color(51, 102, 255));
        btnEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudiante.setText("Estudiante/Maestro");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 190, 40));

        btnMestro.setBackground(new java.awt.Color(51, 102, 255));
        btnMestro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMestro.setForeground(new java.awt.Color(255, 255, 255));
        btnMestro.setText("Administrador");
        btnMestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMestroActionPerformed(evt);
            }
        });
        getContentPane().add(btnMestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 190, 40));

        lbl.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(0, 0, 51));
        lbl.setText("<html><div style='text-align:center;'>El INTECAP es la institución líder en capacitación técnica en Guatemala, que impulsa el talento humano y la productividad con programas de formación y asesoría reconocidos a nivel internacional.<p>¡REGISTRATE!</div></html>");
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 420, 80));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMestroActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed

    }//GEN-LAST:event_btnEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }
    
     private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnMestro;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
