/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import com.umg.proyect.model.Asignacion;
import com.umg.proyect.model.Student;
import com.umg.proyect.service.AsignacionService;
import com.umg.proyect.service.CursoService;
import com.umg.proyect.util.SessionManager;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CPintura extends javax.swing.JFrame {
    private Asignaciones back;
    private final AsignacionService asignacionService;
    private final CursoService cursoService;    
    /**
     * Creates new form CPintura
     */
    public CPintura() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/cp.png");
        this.asignacionService = new AsignacionService();
        this.cursoService = new CursoService();
        cargarDatosUsuario();              
    }
    
    private ImageIcon imagen;
    private Icon icono;
    public void setBack(Asignaciones back) {
        this.back = back;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCarnet = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PINTURA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 450, 110));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnicas", "Acrílico", "Acuarela", "Óleo" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modalidad", "Virtual", "Presencial" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horario", "Lunes 5pm", "Jueves 5pm" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 150, -1));

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 120, 40));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><div style='text-align:center;'>La pintura es una forma de expresión que nos permite transformar emociones e ideas en colores y formas. En este curso aprenderás técnicas básicas y herramientas prácticas para desarrollar tu creatividad y dar vida a tu propio estilo.</div></html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 620, 100));

        btnBack.setText("🏠");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 420, 60, 40));

        lblCarnet.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblCarnet.setForeground(new java.awt.Color(255, 255, 255));
        lblCarnet.setText("****");
        getContentPane().add(lblCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 20));

        lblNombre.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("****");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 20));

        lblfondo.setLabelFor(btnSave);
        lblfondo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblfondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String cursoSeleccionado = (String) jComboBox1.getSelectedItem();
            String modalidadSeleccionada = (String) jComboBox2.getSelectedItem();
            String horarioSeleccionado = (String) jComboBox3.getSelectedItem();

            if ("Tecnica".equals(cursoSeleccionado) ||
                "Modalidad".equals(modalidadSeleccionada) ||
                "Horario".equals(horarioSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Por favor complete todas las selecciones correctamente");
                return;
            }

            Student student = SessionManager.getCurrentStudent();
            if (student == null) {
                JOptionPane.showMessageDialog(this, "No se encontró información del estudiante. Por favor inicie sesión nuevamente.");
                return;
            }

            int idCurso = mapearCursoAId(cursoSeleccionado);
            if (idCurso == -1) {
                JOptionPane.showMessageDialog(this, "Curso no encontrado: " + cursoSeleccionado);
                return;
            }

            Asignacion asignacion = new Asignacion();
            asignacion.setId_student(student.getId());
            asignacion.setId_curse(4);
            asignacion.setModalidad(modalidadSeleccionada);
            asignacion.setHorario(horarioSeleccionado);
            asignacion.setEspecialidad(cursoSeleccionado);

            System.out.println("Enviando asignación: ");
            System.out.println("ID Student: " + student.getId());
            System.out.println("ID Curso: " + idCurso);
            System.out.println("Modalidad: " + modalidadSeleccionada);
            System.out.println("Horario: " + horarioSeleccionado);

            Asignacion resultado = asignacionService.createAsignacion(asignacion);

            if (resultado != null && resultado.getId() > 0) {
                JOptionPane.showMessageDialog(this, "Asignación creada exitosamente");
                limpiarSelecciones();
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear la asignación. Por favor intente nuevamente.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void cargarDatosUsuario() {
        try {
            String userType = SessionManager.getUserType();
            if ("STUDENT".equals(userType)) {
                Student student = SessionManager.getCurrentStudent();
                if (student != null) {
                    String nombre = (student.getNombre() != null) ? student.getNombre() : "Desconocido";
                    String carnet = (student.getCarnet() != null) ? student.getCarnet() : "N/D";
                    lblNombre.setText("Estudiante: " + nombre);
                    lblCarnet.setText("Carnet: " + carnet);
                } else {
                    lblNombre.setText("Estudiante: (no disponible)");
                    lblCarnet.setText("Carnet: (no disponible)");
                }
            } else {
                lblNombre.setText("Usuario no estudiante");
                lblCarnet.setText("");
            }
        } catch (Exception e) {
            lblNombre.setText("Estudiante: (error)");
            lblCarnet.setText("Carnet: (error)");
        }
    }
private int mapearCursoAId(String nombreCurso) {
    return switch (nombreCurso) {
        case "Piano" -> 1;
        case "Guitarra" -> 2;
        case "Violin" -> 3;
        default -> -1;
    };
}
 private void limpiarSelecciones() {
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jComboBox3.setSelectedIndex(0);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPintura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPintura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPintura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPintura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPintura().setVisible(true);
            }
        });
    }
    
     private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
