/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import com.umg.proyect.model.Curso;
import com.umg.proyect.model.Teacher;
import com.umg.proyect.service.AsignacionService;
import com.umg.proyect.service.CursoService;
import com.umg.proyect.util.SessionManager;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Cursos extends javax.swing.JFrame {
    private InicioSesion back;
    private final AsignacionService asignacionService;
    private final CursoService cursoService;    
    public Cursos() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/cursos.png");
        this.Imagen(this.lblPintura, "src/main/java/img/pintura.png");
        this.Imagen(this.lblMusica, "src/main/java/img/musica.png");
        this.Imagen(this.lblidioma, "src/main/java/img/idioma.png");
        this.Imagen(this.lbltec, "src/main/java/img/tec.png");
        this.Imagen(this.lbllogo, "src/main/java/img/logo.png");
        cargarDatosDocente();
    this.asignacionService = new AsignacionService();
    this.cursoService = new CursoService();      
        
    }
    public void setBack(InicioSesion back) {
        this.back = back;
    } 
    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTecno = new javax.swing.JButton();
        btnidioma = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();
        lblMusica = new javax.swing.JLabel();
        btnPintura = new javax.swing.JButton();
        lbltec = new javax.swing.JLabel();
        lblPintura = new javax.swing.JLabel();
        lblidioma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        btnNotas = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTecno.setBackground(new java.awt.Color(51, 51, 255));
        btnTecno.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnTecno.setForeground(new java.awt.Color(255, 255, 255));
        btnTecno.setText("Asignar Curso");
        btnTecno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTecno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 30));

        btnidioma.setBackground(new java.awt.Color(51, 51, 255));
        btnidioma.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnidioma.setForeground(new java.awt.Color(255, 255, 255));
        btnidioma.setText("Asignar Curso");
        btnidioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidiomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 150, 30));

        btnMusica.setBackground(new java.awt.Color(51, 51, 255));
        btnMusica.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica.setText("Asignar Curso");
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 150, 30));
        getContentPane().add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 150));

        btnPintura.setBackground(new java.awt.Color(51, 51, 255));
        btnPintura.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnPintura.setForeground(new java.awt.Color(255, 255, 255));
        btnPintura.setText("Asignar Curso");
        btnPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 30));
        getContentPane().add(lbltec, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 150, 150));
        getContentPane().add(lblPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 150));
        getContentPane().add(lblidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 150));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 3, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("CURSOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 490, 110));
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 60));

        btnBack.setText("Regreso");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        lblNombre.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("****");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, -1));

        lblEspecialidad.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        lblEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecialidad.setText("****");
        getContentPane().add(lblEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 160, -1));

        btnNotas.setText("Evaluacion");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        getContentPane().add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        asignarCursoDocente("Musica");
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinturaActionPerformed
        asignarCursoDocente("Pintura");
    }//GEN-LAST:event_btnPinturaActionPerformed

    private void btnidiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidiomaActionPerformed
        asignarCursoDocente("Idioma");
    }//GEN-LAST:event_btnidiomaActionPerformed

    private void btnTecnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecnoActionPerformed
        asignarCursoDocente("Tecnologia");
    }//GEN-LAST:event_btnTecnoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        Grado login1= new Grado();
        login1.setBack(this);
        login1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNotasActionPerformed

    private void cargarDatosDocente() {
        if (SessionManager.getUserType().equals("TEACHER")) {
            Teacher teacher = SessionManager.getCurrentTeacher();
            lblNombre.setText("Docente: " + teacher.getNombre());
            lblEspecialidad.setText("Especialidad: " + teacher.getEspecialidad());
        }
    }
    
private void asignarCursoDocente(String nombreCurso) {
    try {
        Teacher teacher = SessionManager.getCurrentTeacher();
        if (teacher == null) {
            JOptionPane.showMessageDialog(this, "No se encontró información del docente");
            return;
        }
        
        Curso curso = cursoService.obtenerCursoPorNombre(nombreCurso);
        if (curso == null) {
            JOptionPane.showMessageDialog(this, "Curso no encontrado: " + nombreCurso);
            return;
        }
        
        if (verificarCursoAsignado(teacher.getId(), curso.getId())) {
            JOptionPane.showMessageDialog(this, "Ya tienes asignado el curso: " + nombreCurso);
            return;
        }
        
        curso.setId_teacher(teacher.getId());
        
        Curso cursoActualizado = cursoService.updateCurso(curso.getId(), curso);
        
        if (cursoActualizado != null) {
            JOptionPane.showMessageDialog(this, "Curso '" + nombreCurso + "' asignado exitosamente\n" +
                                               "Ahora eres el docente de este curso");
        } else {
            JOptionPane.showMessageDialog(this, "Error al asignar el curso '" + nombreCurso + "'");
        }
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
}
private boolean verificarCursoAsignado(int idTeacher, int idCurso) throws Exception {
    // Obtener el curso para verificar si ya tiene docente asignado
    Curso curso = cursoService.obtenerCursoPorId(idCurso);
    return curso != null && curso.getId_teacher() == idTeacher;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos().setVisible(true);
            }
        });
    }

    
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnPintura;
    private javax.swing.JButton btnTecno;
    private javax.swing.JButton btnidioma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPintura;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbltec;
    // End of variables declaration//GEN-END:variables
}
