/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class Cursos extends javax.swing.JFrame {
    private Bienvenida back;

    public Cursos() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/cursos.png");
        this.Imagen(this.lblPintura, "src/main/java/img/pintura.png");
        this.Imagen(this.lblMusica, "src/main/java/img/musica.png");
        this.Imagen(this.lblidioma, "src/main/java/img/idioma.png");
        this.Imagen(this.lbltec, "src/main/java/img/tec.png");
        this.Imagen(this.lbllogo, "src/main/java/img/logo.png");
        
    }
    public void setBack(JFrame back) {
        this.back = (Bienvenida) back;
    }    
    private ImageIcon imagen;
    private Icon icono;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntec = new javax.swing.JButton();
        btnidioma = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();
        lblMusica = new javax.swing.JLabel();
        btnPintura = new javax.swing.JButton();
        lbltec = new javax.swing.JLabel();
        lblPintura = new javax.swing.JLabel();
        lblidioma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntec.setBackground(new java.awt.Color(51, 51, 255));
        btntec.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btntec.setForeground(new java.awt.Color(255, 255, 255));
        btntec.setText("Inscribirme");
        btntec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntecActionPerformed(evt);
            }
        });
        getContentPane().add(btntec, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 30));

        btnidioma.setBackground(new java.awt.Color(51, 51, 255));
        btnidioma.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnidioma.setForeground(new java.awt.Color(255, 255, 255));
        btnidioma.setText("Inscribirme");
        btnidioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidiomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 150, 30));

        btnMusica.setBackground(new java.awt.Color(51, 51, 255));
        btnMusica.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica.setText("Inscribirme");
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 150, 30));
        getContentPane().add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 150));

        btnPintura.setBackground(new java.awt.Color(51, 51, 255));
        btnPintura.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnPintura.setForeground(new java.awt.Color(255, 255, 255));
        btnPintura.setText("Inscribirme");
        btnPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 30));
        getContentPane().add(lbltec, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 150, 150));
        getContentPane().add(lblPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 150));
        getContentPane().add(lblidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 150));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 3, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("CURSOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 490, 110));
        getContentPane().add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 60));

        btnBack.setText("Regreso");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPinturaActionPerformed

    private void btnidiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnidiomaActionPerformed

    private void btntecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntecActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cursos().setVisible(true);
            }
        });
    }

    
    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnPintura;
    private javax.swing.JButton btnidioma;
    private javax.swing.JButton btntec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JLabel lblPintura;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblidioma;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lbltec;
    // End of variables declaration//GEN-END:variables
}
