package com.mycompany.sistemaintecap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import com.umg.proyect.model.Student;
import com.umg.proyect.service.StudentService;

import javax.swing.*;

public class InicioSesion extends javax.swing.JFrame {
    private Bienvenida back;
private final StudentService service = new StudentService();  
    public InicioSesion() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/fondo.png");
        this.Imagen(this.lblimg2, "src/main/java/img/chica.png");
    }
    
    private ImageIcon imagen;
    private Icon icono;

    public void setBack(Bienvenida back) {
        this.back = back;
    }
    
    
    /* 
*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblimg2 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        btnRegreso = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Resgistrate!");
        pfondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        pfondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pfondo.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carnet");
        pfondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnetActionPerformed(evt);
            }
        });
        pfondo.add(txtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 200, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gmail");
        pfondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 40, -1));

        btnBuscar.setBackground(new java.awt.Color(51, 51, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Login");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pfondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 280, -1));
        pfondo.add(lblimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 370, 370));

        btnCrear.setBackground(new java.awt.Color(51, 51, 255));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setToolTipText("");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pfondo.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 280, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contraseña");
        pfondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, 20));

        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        pfondo.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 30));

        btnRegreso.setText("Regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });
        pfondo.add(btnRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));
        pfondo.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 760, 470));
        pfondo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 200, 30));

        getContentPane().add(pfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnetActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    try {
        String correo = txtEmail.getText();
        String pass = txtContra.getText();

        int tipo = com.umg.proyect.util.UserRoleChecker.comprobarCorreo(correo);

        switch (tipo) {
            case com.umg.proyect.util.UserRoleChecker.STUDENT -> {
                com.umg.proyect.service.StudentService studentService = new com.umg.proyect.service.StudentService();
                if (studentService.login(correo, pass)) {
                    JOptionPane.showMessageDialog(this, "Login exitoso como ESTUDIANTE");
                } else {
                    JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos (Student)");
                }
            }

            case com.umg.proyect.util.UserRoleChecker.TEACHER -> {
                com.umg.proyect.service.TeacherService teacherService = new com.umg.proyect.service.TeacherService();
                if (teacherService.login(correo, pass)) {
                    JOptionPane.showMessageDialog(this, "Login exitoso como DOCENTE");
                } else {
                    JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos (Teacher)");
                }
            }

            default -> JOptionPane.showMessageDialog(this, "Dominio de correo no válido");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "️ Error en login: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
    try {
        String correo = txtEmail.getText();
        String pass = txtContra.getText();
        String nombre = jTextField1.getText();

        int tipo = com.umg.proyect.util.UserRoleChecker.comprobarCorreo(correo);

        switch (tipo) {
            case com.umg.proyect.util.UserRoleChecker.STUDENT -> {
                com.umg.proyect.model.Student s = new com.umg.proyect.model.Student();
                s.setNombre(nombre);
                s.setEmail(correo);
                s.setPassword(pass);
                s.setCarnet(txtCarnet.getText());
                service.createStudent(s);
                JOptionPane.showMessageDialog(this, "Estudiante agregado correctamente.");
            }

            case com.umg.proyect.util.UserRoleChecker.TEACHER -> {
                com.umg.proyect.model.Teacher t = new com.umg.proyect.model.Teacher();
                t.setNombre(nombre);
                t.setEmail(correo);
                t.setPassword(pass);
                new com.umg.proyect.service.TeacherService().createTeacher(t);
                JOptionPane.showMessageDialog(this, "Docente agregado correctamente.");
            }

            default -> JOptionPane.showMessageDialog(this, "Dominio de correo no válido, no se pudo registrar.");
        }

        cleanFields();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al agregar usuario: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresoActionPerformed

    /**
     * @param args the command line arguments
     */

        private void cleanFields(){
        jTextField1.setText("");
        txtEmail.setText("");
        txtContra.setText("");
        txtCarnet.setText("");
    }    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JPanel pfondo;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}