/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaintecap;

import com.umg.proyect.service.AdminService;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Maestros extends javax.swing.JFrame {
    private Bienvenida back;
    boolean showPassword = false;   
    private final AdminService service1 = new AdminService();    
    /**
     * Creates new form Maestros
     */
    public Maestros() {
        initComponents();
        
        this.setLocationRelativeTo(this);
        this.Imagen(this.lblfondo, "src/main/java/img/fondo.png");
        this.Imagen(this.lblimg, "src/main/java/img/maestro.png");
    }
  private ImageIcon imagen;
  private Icon icono;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        passClave = new javax.swing.JPasswordField();
        lblMostrar = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 190, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 10));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 30));

        btnBuscar.setBackground(new java.awt.Color(51, 51, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Login");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 280, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 50, 10));
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 320, 390));

        btnBack.setText("Regreso");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        passClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passClaveMouseClicked(evt);
            }
        });
        passClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passClaveActionPerformed(evt);
            }
        });
        getContentPane().add(passClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 200, 30));

        lblMostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(255, 255, 51));
        lblMostrar.setText("Mostrar");
        lblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setBack(Bienvenida back) {
        this.back = back;
    }

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    try {
        String correo = txtEmail.getText();
        String pass = new String(passClave.getPassword());

        int tipo = com.umg.proyect.util.UserRoleChecker.comprobarCorreo(correo);

        switch (tipo) {
            case com.umg.proyect.util.UserRoleChecker.ADMIN -> {
                com.umg.proyect.service.AdminService adminService = new com.umg.proyect.service.AdminService();
                if (adminService.login(correo, pass)) {
                    JOptionPane.showMessageDialog(this, "Login exitoso como Administrador");
                    Configuracion asig = new Configuracion();
                    asig.setBack(this);
                    asig.setVisible(true);
                    this.setVisible(false);                    
                } else {
                    JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos (Admin)");
                }
            }
            default -> JOptionPane.showMessageDialog(this, "Correo Invalido");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "️ Error en login: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void passClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passClaveActionPerformed

    private void passClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passClaveMouseClicked

    }//GEN-LAST:event_passClaveMouseClicked

    private void lblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseClicked
        if (showPassword) {
            passClave.setEchoChar('\u2022');
            lblMostrar.setText("Mostrar");
        } else {
            passClave.setEchoChar((char) 0);
            lblMostrar.setText("Ocultar");
        }
        showPassword = !showPassword;
    }//GEN-LAST:event_lblMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maestros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maestros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maestros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maestros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maestros().setVisible(true);
            }
        });
    }
    
    
     private void Imagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblimg;
    private javax.swing.JPasswordField passClave;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
